/* Generated By:JavaCC: Do not edit this line. AssignmentTwoVisitor.java Version 7.0.2 */
public interface AssignmentTwoVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTConstDecl node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTReturnValue node, Object data);
  public Object visit(ASTParameter_list node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTMinus_sign node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTAdd_Op node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTLogicalAND node, Object data);
  public Object visit(ASTLogicalOR node, Object data);
  public Object visit(ASTCompare node, Object data);
  public Object visit(ASTEquals node, Object data);
  public Object visit(ASTNot_Equals node, Object data);
  public Object visit(ASTLess_Than node, Object data);
  public Object visit(ASTLess_Than_Or_Equal node, Object data);
  public Object visit(ASTGreater_Than node, Object data);
  public Object visit(ASTGreater_Than_Or_Equal node, Object data);
  public Object visit(ASTArg_list node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTMain node, Object data);
}
/* JavaCC - OriginalChecksum=5a05f4f06643598289dcc9f9c4777e29 (do not edit this line) */
