/* Generated By:JavaCC: Do not edit this line. AssignmentTwoTreeConstants.java Version 7.0.2 */
public interface AssignmentTwoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTRETURNVALUE = 5;
  public int JJTPARAMETER_LIST = 6;
  public int JJTPARAMETER = 7;
  public int JJTSTATEMENT = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTMINUS_SIGN = 10;
  public int JJTBOOLEAN = 11;
  public int JJTADD_OP = 12;
  public int JJTFUNCTIONCALL = 13;
  public int JJTLOGICALAND = 14;
  public int JJTLOGICALOR = 15;
  public int JJTCOMPARE = 16;
  public int JJTEQUALS = 17;
  public int JJTNOT_EQUALS = 18;
  public int JJTLESS_THAN = 19;
  public int JJTLESS_THAN_OR_EQUAL = 20;
  public int JJTGREATER_THAN = 21;
  public int JJTGREATER_THAN_OR_EQUAL = 22;
  public int JJTARG_LIST = 23;
  public int JJTNUMBER = 24;
  public int JJTIDENTIFIER = 25;
  public int JJTTYPE = 26;
  public int JJTMAIN = 27;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VarDecl",
    "ConstDecl",
    "Function",
    "ReturnValue",
    "Parameter_list",
    "Parameter",
    "Statement",
    "Assignment",
    "Minus_sign",
    "Boolean",
    "Add_Op",
    "FunctionCall",
    "LogicalAND",
    "LogicalOR",
    "Compare",
    "Equals",
    "Not_Equals",
    "Less_Than",
    "Less_Than_Or_Equal",
    "Greater_Than",
    "Greater_Than_Or_Equal",
    "Arg_list",
    "Number",
    "Identifier",
    "Type",
    "Main",
  };
}
/* JavaCC - OriginalChecksum=e58759cd3ab869a410b5cfc12eedb316 (do not edit this line) */
