/* Generated By:JJTree: Do not edit this line. ASTFunctionCallReturn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionCallReturn extends SimpleNode {
  public ASTFunctionCallReturn(int id) {
    super(id);
  }

  public ASTFunctionCallReturn(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=54bee2b665e392d3f94cc5d08257c99c (do not edit this line) */
