/* Generated By:JJTree: Do not edit this line. ASTFuncReturn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFuncReturn extends SimpleNode {
  public ASTFuncReturn(int id) {
    super(id);
  }

  public ASTFuncReturn(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52766fe0492096083a39ad9cbc44ea33 (do not edit this line) */
