/* Generated By:JJTree: Do not edit this line. ASTLogical_Conjunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogical_Conjunction extends SimpleNode {
  public ASTLogical_Conjunction(int id) {
    super(id);
  }

  public ASTLogical_Conjunction(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=77678be6ea54553cc12667f98c83ba95 (do not edit this line) */
