/* Generated By:JJTree: Do not edit this line. ASTLogicalAND.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalAND extends SimpleNode {
  public ASTLogicalAND(int id) {
    super(id);
  }

  public ASTLogicalAND(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=730300d510f79fc4bd302c7b3ea7acc8 (do not edit this line) */
