/* Generated By:JJTree: Do not edit this line. ASTNot_Equals.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNot_Equals extends SimpleNode {
  public ASTNot_Equals(int id) {
    super(id);
  }

  public ASTNot_Equals(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0484c6c489932feb200cc75719e6c209 (do not edit this line) */
