/* Generated By:JJTree: Do not edit this line. ASTStatement_Begin_Structure.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement_Begin_Structure extends SimpleNode {
  public ASTStatement_Begin_Structure(int id) {
    super(id);
  }

  public ASTStatement_Begin_Structure(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0d4f17329c68cf490329323202556bc8 (do not edit this line) */
