/* Generated By:JavaCC: Do not edit this line. AssignmentTwoTreeConstants.java Version 7.0.2 */
public interface AssignmentTwoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFUNCTIONLIST = 1;
  public int JJTDECLARATIONLIST = 2;
  public int JJTVOID = 3;
  public int JJTVARDECL = 4;
  public int JJTCONSTDECL = 5;
  public int JJTFUNCTION = 6;
  public int JJTSTATEMENT_BLOCK = 7;
  public int JJTRETURN = 8;
  public int JJTPARAMETER_LIST = 9;
  public int JJTPARAMETER = 10;
  public int JJTSTATEMENT = 11;
  public int JJTCONDITION = 12;
  public int JJTMINUS_SIGN = 13;
  public int JJTEXP = 14;
  public int JJTADD_OP = 15;
  public int JJTMINUS_OP = 16;
  public int JJTBRACKET_EXPRESSION = 17;
  public int JJTNOT_OP = 18;
  public int JJTLOGICAL_CONJUNCTION = 19;
  public int JJTLOGICAL_DISJUNCTION = 20;
  public int JJTBRACKET_CONDITION = 21;
  public int JJTEQUALS = 22;
  public int JJTNOT_EQUALS = 23;
  public int JJTLESS_THAN = 24;
  public int JJTLESS_THAN_OR_EQUAL = 25;
  public int JJTGREATER_THAN = 26;
  public int JJTGREATER_THAN_OR_EQUAL = 27;
  public int JJTARG_LIST = 28;
  public int JJTNEMP_ARG_LIST = 29;
  public int JJTASSIGNMENT_STRUCTURE = 30;
  public int JJTFUNCTION_CALL_STRUCTURE = 31;
  public int JJTSTATEMENT_BEGIN_STRUCTURE = 32;
  public int JJTNUMBER = 33;
  public int JJTIDENTIFIER = 34;
  public int JJTTYPE = 35;
  public int JJTMAIN = 36;


  public String[] jjtNodeName = {
    "Program",
    "FunctionList",
    "DeclarationList",
    "void",
    "VarDecl",
    "ConstDecl",
    "Function",
    "Statement_block",
    "Return",
    "Parameter_list",
    "Parameter",
    "Statement",
    "Condition",
    "Minus_sign",
    "Exp",
    "Add_Op",
    "Minus_Op",
    "Bracket_Expression",
    "Not_op",
    "Logical_Conjunction",
    "Logical_Disjunction",
    "Bracket_Condition",
    "Equals",
    "Not_Equals",
    "Less_Than",
    "Less_Than_Or_Equal",
    "Greater_Than",
    "Greater_Than_Or_Equal",
    "Arg_list",
    "Nemp_arg_list",
    "Assignment_structure",
    "Function_call_structure",
    "Statement_Begin_Structure",
    "Number",
    "Identifier",
    "Type",
    "Main",
  };
}
/* JavaCC - OriginalChecksum=3542815b2366c7140760ba7416e1652e (do not edit this line) */
