/* Generated By:JavaCC: Do not edit this line. AssignmentTwoTreeConstants.java Version 7.0.2 */
public interface AssignmentTwoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFUNCTIONLIST = 1;
  public int JJTDECLARATIONLIST = 2;
  public int JJTVOID = 3;
  public int JJTVARDECL = 4;
  public int JJTCONSTDECL = 5;
  public int JJTFUNCTION = 6;
  public int JJTSTATEMENT_BLOCK = 7;
  public int JJTRETURN = 8;
  public int JJTPARAMETER_LIST = 9;
  public int JJTPARAMETER = 10;
  public int JJTSTATEMENT = 11;
  public int JJTARG_LIST = 12;
  public int JJTMINUS_SIGN = 13;
  public int JJTBOOLEAN = 14;
  public int JJTEXP = 15;
  public int JJTADD_OP = 16;
  public int JJTLOGICAL_CONJUNCTION = 17;
  public int JJTLOGICAL_DISJUNCTION = 18;
  public int JJTEQUALS = 19;
  public int JJTNOT_EQUALS = 20;
  public int JJTLESS_THAN = 21;
  public int JJTLESS_THAN_OR_EQUAL = 22;
  public int JJTGREATER_THAN = 23;
  public int JJTGREATER_THAN_OR_EQUAL = 24;
  public int JJTNUMBER = 25;
  public int JJTIDENTIFIER = 26;
  public int JJTTYPE = 27;
  public int JJTMAIN = 28;


  public String[] jjtNodeName = {
    "Program",
    "FunctionList",
    "DeclarationList",
    "void",
    "VarDecl",
    "ConstDecl",
    "Function",
    "Statement_block",
    "Return",
    "Parameter_list",
    "Parameter",
    "Statement",
    "Arg_list",
    "Minus_sign",
    "Boolean",
    "Exp",
    "Add_Op",
    "Logical_Conjunction",
    "Logical_Disjunction",
    "Equals",
    "Not_Equals",
    "Less_Than",
    "Less_Than_Or_Equal",
    "Greater_Than",
    "Greater_Than_Or_Equal",
    "Number",
    "Identifier",
    "Type",
    "Main",
  };
}
/* JavaCC - OriginalChecksum=ad922b8c4e9b0d3748e14ace5fb806ef (do not edit this line) */
