/* Generated By:JavaCC: Do not edit this line. AssignmentTwoTreeConstants.java Version 7.0.2 */
public interface AssignmentTwoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFUNCTION_LIST = 1;
  public int JJTDEC_LIST = 2;
  public int JJTDECL = 3;
  public int JJTVOID = 4;
  public int JJTVAR_DECL = 5;
  public int JJTCONST_DECL = 6;
  public int JJTFUNCTION = 7;
  public int JJTSTATEMENT_BLOCK = 8;
  public int JJTRETURN = 9;
  public int JJTPARAMETER_LIST = 10;
  public int JJTNEMP_PARAMETER_LIST = 11;
  public int JJTSTATEMENT = 12;
  public int JJTMINUS_SIGN = 13;
  public int JJTBINARY_ARITH_OP = 14;
  public int JJTEXP = 15;
  public int JJTCONDITION = 16;
  public int JJTNOT_OP = 17;
  public int JJTBINARY_LOGICAL_OP = 18;
  public int JJTCOMPARISON_OP = 19;
  public int JJTARG_LIST = 20;
  public int JJTNEMP_ARG_LIST = 21;
  public int JJTASSIGNMENT_EXP = 22;
  public int JJTFUNCTION_CALL_STATEMENT = 23;
  public int JJTNUMBER = 24;
  public int JJTIDENTIFIER = 25;
  public int JJTANYTYPE = 26;
  public int JJTTYPEINTEGER = 27;
  public int JJTTYPEBOOLEAN = 28;
  public int JJTMAIN = 29;


  public String[] jjtNodeName = {
    "program",
    "Function_list",
    "Dec_list",
    "Decl",
    "void",
    "Var_decl",
    "Const_decl",
    "Function",
    "Statement_block",
    "Return",
    "Parameter_list",
    "Nemp_parameter_list",
    "Statement",
    "Minus_sign",
    "Binary_arith_op",
    "Exp",
    "Condition",
    "Not_op",
    "Binary_logical_op",
    "Comparison_op",
    "Arg_list",
    "Nemp_arg_list",
    "Assignment_exp",
    "Function_call_statement",
    "number",
    "identifier",
    "anyType",
    "typeInteger",
    "typeBoolean",
    "Main",
  };
}
/* JavaCC - OriginalChecksum=92cc14475aa9d9e5d56285b1b4f80040 (do not edit this line) */
