/* Generated By:JJTree: Do not edit this line. ASTAdd_Op.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdd_Op extends SimpleNode {
  public ASTAdd_Op(int id) {
    super(id);
  }

  public ASTAdd_Op(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0303cc58dd3ec98ea3a083b1cd96bee5 (do not edit this line) */
