/* Generated By:JJTree: Do not edit this line. ASTAssignment_structure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignment_structure extends SimpleNode {
  public ASTAssignment_structure(int id) {
    super(id);
  }

  public ASTAssignment_structure(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b92631745efc71c382a1a4c58c6c112d (do not edit this line) */
