/* Generated By:JJTree: Do not edit this line. ASTAssignment_exp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignment_exp extends SimpleNode {
  public ASTAssignment_exp(int id) {
    super(id);
  }

  public ASTAssignment_exp(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3705dcdd760a47a6391c5a6a8d2b8661 (do not edit this line) */
