/* Generated By:JJTree: Do not edit this line. ASTBracket_Condition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracket_Condition extends SimpleNode {
  public ASTBracket_Condition(int id) {
    super(id);
  }

  public ASTBracket_Condition(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5ba17606a25c17b8bc243a7f6987be3d (do not edit this line) */
