/* Generated By:JJTree: Do not edit this line. ASTbinary_logical_op.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbinary_logical_op extends SimpleNode {
  public ASTbinary_logical_op(int id) {
    super(id);
  }

  public ASTbinary_logical_op(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5d09c5d2e4d7f65b380e1aa8430a8207 (do not edit this line) */
