/* Generated By:JJTree: Do not edit this line. ASTBracket_Condition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracket_Condition extends SimpleNode {
  public ASTBracket_Condition(int id) {
    super(id);
  }

  public ASTBracket_Condition(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=256603aa1895e6894399dc458aea962f (do not edit this line) */
