/* Generated By:JJTree: Do not edit this line. ASTBracket_Expression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracket_Expression extends SimpleNode {
  public ASTBracket_Expression(int id) {
    super(id);
  }

  public ASTBracket_Expression(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ca9b254d39a9d9a4b268754a5b517fb (do not edit this line) */
