/* Generated By:JJTree: Do not edit this line. ASTBinary_mult_op.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBinary_mult_op extends SimpleNode {
  public ASTBinary_mult_op(int id) {
    super(id);
  }

  public ASTBinary_mult_op(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc52bf96accc95be0b24bbef5994bed3 (do not edit this line) */
