/* Generated By:JJTree: Do not edit this line. ASTComparison_op.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComparison_op extends SimpleNode {
  public ASTComparison_op(int id) {
    super(id);
  }

  public ASTComparison_op(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df6b2dc4a5b03768bd327c7b45582384 (do not edit this line) */
