/* Generated By:JJTree: Do not edit this line. ASTDiv_Op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv_Op extends SimpleNode {
  public ASTDiv_Op(int id) {
    super(id);
  }

  public ASTDiv_Op(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c265d8e14c0bba5b9755b9aaaf4aaac5 (do not edit this line) */
