/* Generated By:JJTree: Do not edit this line. ASTFunction_call_statement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction_call_statement extends SimpleNode {
  public ASTFunction_call_statement(int id) {
    super(id);
  }

  public ASTFunction_call_statement(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=837ab88af0e37f79dac7b694b3db24b9 (do not edit this line) */
