/* Generated By:JJTree: Do not edit this line. ASTGreater_Than.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreater_Than extends SimpleNode {
  public ASTGreater_Than(int id) {
    super(id);
  }

  public ASTGreater_Than(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=01a720816ec992d361c7aca09227b270 (do not edit this line) */
