/* Generated By:JJTree: Do not edit this line. ASTLogical_Conjunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogical_Conjunction extends SimpleNode {
  public ASTLogical_Conjunction(int id) {
    super(id);
  }

  public ASTLogical_Conjunction(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c88910bd182220a11be9e9a6a4e2732c (do not edit this line) */
