/* Generated By:JJTree: Do not edit this line. ASTLess_Than.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLess_Than extends SimpleNode {
  public ASTLess_Than(int id) {
    super(id);
  }

  public ASTLess_Than(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=31063e1984503b2a1ad3a5eb47451c93 (do not edit this line) */
