/* Generated By:JJTree: Do not edit this line. ASTMinus_Op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinus_Op extends SimpleNode {
  public ASTMinus_Op(int id) {
    super(id);
  }

  public ASTMinus_Op(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e21769b2fc872bd6b94a636f35f23005 (do not edit this line) */
