/* Generated By:JJTree: Do not edit this line. ASTMinus_sign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinus_sign extends SimpleNode {
  public ASTMinus_sign(int id) {
    super(id);
  }

  public ASTMinus_sign(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ee12b53fda0fc966f6c7f9f0bfffd90 (do not edit this line) */
