/* Generated By:JJTree: Do not edit this line. ASTMainMethod.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethod extends SimpleNode {
  public ASTMainMethod(int id) {
    super(id);
  }

  public ASTMainMethod(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=589c9b0a1dc5f1fde466b1fd8d2340cb (do not edit this line) */
