/* Generated By:JJTree: Do not edit this line. ASTNemp_arg_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNemp_arg_list extends SimpleNode {
  public ASTNemp_arg_list(int id) {
    super(id);
  }

  public ASTNemp_arg_list(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bb048d3f7e3bbaf1336271eb17e31b97 (do not edit this line) */
