/* Generated By:JJTree: Do not edit this line. ASTNot_Equals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNot_Equals extends SimpleNode {
  public ASTNot_Equals(int id) {
    super(id);
  }

  public ASTNot_Equals(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59e4f2db717bb67fca4bb24478fbbfb7 (do not edit this line) */
