/* Generated By:JJTree: Do not edit this line. ASTsimple_condition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsimple_condition extends SimpleNode {
  public ASTsimple_condition(int id) {
    super(id);
  }

  public ASTsimple_condition(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e103e1316702a150f8e198e00d3ef82c (do not edit this line) */
