/* Generated By:JJTree: Do not edit this line. ASTStatement_Block.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement_Block extends SimpleNode {
  public ASTStatement_Block(int id) {
    super(id);
  }

  public ASTStatement_Block(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bf1de026813fbb5fc3655ca22f3c320d (do not edit this line) */
