/* Generated By:JJTree: Do not edit this line. ASTStatement_begin_structure.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement_begin_structure extends SimpleNode {
  public ASTStatement_begin_structure(int id) {
    super(id);
  }

  public ASTStatement_begin_structure(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9f2a34dcfb752203fe34658ec9e334d3 (do not edit this line) */
