/* Generated By:JJTree: Do not edit this line. ASTspecial_expression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTspecial_expression extends SimpleNode {
  public ASTspecial_expression(int id) {
    super(id);
  }

  public ASTspecial_expression(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=98b0b0f5259ab6fa9edd8cce9b19c56d (do not edit this line) */
