/* Generated By:JJTree: Do not edit this line. ASTSimple_condition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSimple_condition extends SimpleNode {
  public ASTSimple_condition(int id) {
    super(id);
  }

  public ASTSimple_condition(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9f5dd7b3824a2876a1fae94398b31fd (do not edit this line) */
