/* Generated By:JJTree: Do not edit this line. ASTStatement_block.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement_block extends SimpleNode {
  public ASTStatement_block(int id) {
    super(id);
  }

  public ASTStatement_block(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ec55e8712b84b41a6ad64dbb74fcd1c8 (do not edit this line) */
