/* Generated By:JJTree: Do not edit this line. ASTStatement_Begin_Structure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement_Begin_Structure extends SimpleNode {
  public ASTStatement_Begin_Structure(int id) {
    super(id);
  }

  public ASTStatement_Begin_Structure(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=06b50019de0e46e03f39a9dc9ae35940 (do not edit this line) */
