/* Generated By:JJTree: Do not edit this line. ASTsimple_special_expression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsimple_special_expression extends SimpleNode {
  public ASTsimple_special_expression(int id) {
    super(id);
  }

  public ASTsimple_special_expression(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d27472ab9a2057c89f546f3c44893d0e (do not edit this line) */
