/* Generated By:JJTree: Do not edit this line. ASTtypeVoid.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtypeVoid extends SimpleNode {
  public ASTtypeVoid(int id) {
    super(id);
  }

  public ASTtypeVoid(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4da1b7fef3c98d87e6dff61adab7db42 (do not edit this line) */
