/* Generated By:JJTree: Do not edit this line. ASTVar_decl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVar_decl extends SimpleNode {
  public ASTVar_decl(int id) {
    super(id);
  }

  public ASTVar_decl(AssignmentTwo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AssignmentTwoVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=913b5c8cbcafd6d168544ccbffe1b5d5 (do not edit this line) */
